<?php


namespace app\admin\controller;


use app\common\services\menu\MenuGroupService;
use app\common\services\menu\MenuService;
use think\Controller;

class BaseController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        if (!session('user')) {
//            return $this->redirect('login/index');
//        }
        $this->getMenu();
    }

    /*
     * 获取菜单
     */
    public function getMenu()
    {
        $lists = [];
        $menu_service = new MenuService();
        $menu_group_service = new MenuGroupService();
        $menu_groups = $menu_group_service->getMenuGroups();
        $menus = $menu_service->getMenus();
        foreach ($menu_groups as $key => $menu_group) {
            $lists[$menu_group['id']] = [
                'id'    =>  $menu_group['id'],
                'name'  =>  $menu_group['name'],
                'icon'  =>  $menu_group['icon'],
                'child' =>  []
            ];
        }
        foreach ($menus as $menu){
            if(isset($lists[$menu['pid']])){
                array_push($lists[$menu['pid']]['child'], [
                    'id'    =>  $menu['id'],
                    'name'  =>  $menu['name'],
                    'url'   =>  $menu['url']
                ]);
            }
        }

        $this->assign('menus',$menus);
        $this->assign('menu_groups',$menu_groups);
        $this->assign('menu_lists',$lists);
    }
}